-- Generated by scripts/postgres-to-mysql8-export.js

CREATE DATABASE IF NOT EXISTS `story` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `story`;

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_api_key`;

CREATE TABLE `admin_api_key` (
  `id` CHAR(36) NOT NULL,
  `client_name` LONGTEXT NOT NULL,
  `key_prefix` LONGTEXT NOT NULL,
  `client_secret_hash` LONGTEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `revoked_at` DATETIME(6) NULL,
  `last_used_at` DATETIME(6) NULL,
  `created_by_admin_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_admin_api_key_created_by_admin_user_id` (`created_by_admin_user_id`),
  CONSTRAINT `fk_admin_api_key_created_by_admin_user_id` FOREIGN KEY (`created_by_admin_user_id`) REFERENCES `admin_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `admin_session`;

CREATE TABLE `admin_session` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `issued_at` DATETIME(6) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  `revoked_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_admin_session_user_id` (`user_id`),
  CONSTRAINT `fk_admin_session_user_id` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `admin_user`;

CREATE TABLE `admin_user` (
  `id` CHAR(36) NOT NULL,
  `email` LONGTEXT NOT NULL,
  `role` VARCHAR(191) NOT NULL DEFAULT 'super_admin',
  `password_hash` LONGTEXT NOT NULL,
  `must_change_password` TINYINT(1) NOT NULL DEFAULT 1,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `asset`;

CREATE TABLE `asset` (
  `id` CHAR(36) NOT NULL,
  `kind` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `media_type` VARCHAR(191) NOT NULL,
  `storage_key` LONGTEXT NOT NULL,
  `public_url` LONGTEXT NOT NULL,
  `source_file_name` LONGTEXT NULL,
  `mime_type` LONGTEXT NOT NULL,
  `bytes` BIGINT NOT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `duration_ms` INT NULL,
  `checksum_sha256` LONGTEXT NOT NULL,
  `created_by_admin_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_asset_created_by_admin_user_id` (`created_by_admin_user_id`),
  CONSTRAINT `fk_asset_created_by_admin_user_id` FOREIGN KEY (`created_by_admin_user_id`) REFERENCES `admin_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `client`;

CREATE TABLE `client` (
  `id` CHAR(36) NOT NULL,
  `client_id` LONGTEXT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `placement`;

CREATE TABLE `placement` (
  `id` CHAR(36) NOT NULL,
  `placement_key` LONGTEXT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `description` LONGTEXT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `records`;

CREATE TABLE `records` (
  `sequence_id` BIGINT NOT NULL,
  `table_name` VARCHAR(128) NOT NULL,
  `id` VARCHAR(191) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `updated_at` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`table_name`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `schema_migrations`;

CREATE TABLE `schema_migrations` (
  `id` LONGTEXT NOT NULL,
  `applied_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `static_token`;

CREATE TABLE `static_token` (
  `id` CHAR(36) NOT NULL,
  `client_id` CHAR(36) NOT NULL,
  `token_hash` LONGTEXT NOT NULL,
  `token_prefix` LONGTEXT NOT NULL,
  `label` LONGTEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `revoked_at` DATETIME(6) NULL,
  `expires_at` DATETIME(6) NULL,
  `last_used_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_static_token_client_id` (`client_id`),
  CONSTRAINT `fk_static_token_client_id` FOREIGN KEY (`client_id`) REFERENCES `client` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story`;

CREATE TABLE `story` (
  `id` CHAR(36) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
  `current_draft_revision_id` CHAR(36) NOT NULL,
  `current_published_revision_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group`;

CREATE TABLE `story_group` (
  `id` CHAR(36) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
  `current_draft_revision_id` CHAR(36) NOT NULL,
  `current_published_revision_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group_revision`;

CREATE TABLE `story_group_revision` (
  `id` CHAR(36) NOT NULL,
  `story_group_id` CHAR(36) NOT NULL,
  `revision_no` INT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `bottom_label` LONGTEXT NULL,
  `logo_asset_id` CHAR(36) NOT NULL,
  `badge_kind` LONGTEXT NULL,
  `badge_value` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL,
  `created_by_admin_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_group_revision_created_by_admin_user_id` (`created_by_admin_user_id`),
  CONSTRAINT `fk_story_group_revision_created_by_admin_user_id` FOREIGN KEY (`created_by_admin_user_id`) REFERENCES `admin_user` (`id`),
  KEY `idx_story_group_revision_logo_asset_id` (`logo_asset_id`),
  CONSTRAINT `fk_story_group_revision_logo_asset_id` FOREIGN KEY (`logo_asset_id`) REFERENCES `asset` (`id`),
  KEY `idx_story_group_revision_story_group_id` (`story_group_id`),
  CONSTRAINT `fk_story_group_revision_story_group_id` FOREIGN KEY (`story_group_id`) REFERENCES `story_group` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group_revision_story`;

CREATE TABLE `story_group_revision_story` (
  `id` CHAR(36) NOT NULL,
  `story_group_revision_id` CHAR(36) NOT NULL,
  `story_id` CHAR(36) NOT NULL,
  `sort_order` INT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_group_revision_story_story_group_revision_id` (`story_group_revision_id`),
  CONSTRAINT `fk_story_group_revision_story_story_group_revision_id` FOREIGN KEY (`story_group_revision_id`) REFERENCES `story_group_revision` (`id`),
  KEY `idx_story_group_revision_story_story_id` (`story_id`),
  CONSTRAINT `fk_story_group_revision_story_story_id` FOREIGN KEY (`story_id`) REFERENCES `story` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group_set`;

CREATE TABLE `story_group_set` (
  `id` CHAR(36) NOT NULL,
  `placement_id` CHAR(36) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `is_fallback` TINYINT(1) NOT NULL DEFAULT 0,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
  `current_draft_revision_id` CHAR(36) NOT NULL,
  `current_published_revision_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_group_set_placement_id` (`placement_id`),
  CONSTRAINT `fk_story_group_set_placement_id` FOREIGN KEY (`placement_id`) REFERENCES `placement` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group_set_revision`;

CREATE TABLE `story_group_set_revision` (
  `id` CHAR(36) NOT NULL,
  `story_group_set_id` CHAR(36) NOT NULL,
  `revision_no` INT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `status` LONGTEXT NOT NULL,
  `target_platforms` JSON NOT NULL DEFAULT '{}',
  `ios_min_app_version` LONGTEXT NULL,
  `android_min_app_version` LONGTEXT NULL,
  `target_segments` JSON NOT NULL DEFAULT '{}',
  `created_by_admin_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_group_set_revision_created_by_admin_user_id` (`created_by_admin_user_id`),
  CONSTRAINT `fk_story_group_set_revision_created_by_admin_user_id` FOREIGN KEY (`created_by_admin_user_id`) REFERENCES `admin_user` (`id`),
  KEY `idx_story_group_set_revision_story_group_set_id` (`story_group_set_id`),
  CONSTRAINT `fk_story_group_set_revision_story_group_set_id` FOREIGN KEY (`story_group_set_id`) REFERENCES `story_group_set` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_group_set_revision_group`;

CREATE TABLE `story_group_set_revision_group` (
  `id` CHAR(36) NOT NULL,
  `story_group_set_revision_id` CHAR(36) NOT NULL,
  `story_group_id` CHAR(36) NOT NULL,
  `sort_order` INT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_group_set_revision_group_story_group_id` (`story_group_id`),
  CONSTRAINT `fk_story_group_set_revision_group_story_group_id` FOREIGN KEY (`story_group_id`) REFERENCES `story_group` (`id`),
  KEY `idx_story_group_set_revision_group_story_group_set_revision_id` (`story_group_set_revision_id`),
  CONSTRAINT `fk_story_group_set_revision_group_story_group_set_revision_id` FOREIGN KEY (`story_group_set_revision_id`) REFERENCES `story_group_set_revision` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `story_revision`;

CREATE TABLE `story_revision` (
  `id` CHAR(36) NOT NULL,
  `story_id` CHAR(36) NOT NULL,
  `revision_no` INT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `media_type` VARCHAR(191) NOT NULL,
  `media_asset_id` CHAR(36) NOT NULL,
  `video_poster_asset_id` CHAR(36) NULL,
  `image_duration_ms` INT NULL,
  `cta_label` LONGTEXT NULL,
  `cta_type` VARCHAR(191) NULL,
  `cta_value` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL,
  `created_by_admin_user_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_story_revision_created_by_admin_user_id` (`created_by_admin_user_id`),
  CONSTRAINT `fk_story_revision_created_by_admin_user_id` FOREIGN KEY (`created_by_admin_user_id`) REFERENCES `admin_user` (`id`),
  KEY `idx_story_revision_media_asset_id` (`media_asset_id`),
  CONSTRAINT `fk_story_revision_media_asset_id` FOREIGN KEY (`media_asset_id`) REFERENCES `asset` (`id`),
  KEY `idx_story_revision_story_id` (`story_id`),
  CONSTRAINT `fk_story_revision_story_id` FOREIGN KEY (`story_id`) REFERENCES `story` (`id`),
  KEY `idx_story_revision_video_poster_asset_id` (`video_poster_asset_id`),
  CONSTRAINT `fk_story_revision_video_poster_asset_id` FOREIGN KEY (`video_poster_asset_id`) REFERENCES `asset` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
